<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Quiz\Module'                         => __DIR__ . '/Module.php',
  'Quiz\Controller\MainController'      => __DIR__ . '/src/Quiz/Controller/MainController.php',
  'Quiz\Document\Quiz\Choice'           => __DIR__ . '/src/Quiz/Document/Quiz/Choice.php',
  'Quiz\Document\Quiz\Question'         => __DIR__ . '/src/Quiz/Document/Quiz/Question.php',
  'Quiz\Document\Quiz'                  => __DIR__ . '/src/Quiz/Document/Quiz.php',
  'Quiz\Document\Result'                => __DIR__ . '/src/Quiz/Document/Result.php',
  'Quiz\Service\QuizService'            => __DIR__ . '/src/Quiz/Service/QuizService.php',
  'Quiz\Service\ResultService'          => __DIR__ . '/src/Quiz/Service/ResultService.php',
  'QuizTest\Bootstrap'                  => __DIR__ . '/tests/Bootstrap.php',
  'QuizTest\AbstractControllerZendtest' => __DIR__ . '/tests/QuizTest/AbstractControllerZendtest.php',
  'QuizTest\AbstractTestCase'           => __DIR__ . '/tests/QuizTest/AbstractTestCase.php',
  'QuizTest\Tests\IndexControllerTest'  => __DIR__ . '/tests/QuizTest/Tests/IndexControllerTest.php',
  'QuizTest\Tests\QuizServiceTest'      => __DIR__ . '/tests/QuizTest/Tests/QuizServiceTest.php',
);
