<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'User\Module'                               => __DIR__ . '/Module.php',
  'User\Controller\ManageController'          => __DIR__ . '/src/User/Controller/ManageController.php',
  'User\Document\User\Address'                => __DIR__ . '/src/User/Document/User/Address.php',
  'User\Document\User\Facebook'               => __DIR__ . '/src/User/Document/User/Facebook.php',
  'User\Document\User\Phonenumber'            => __DIR__ . '/src/User/Document/User/Phonenumber.php',
  'User\Document\User\Seller'                 => __DIR__ . '/src/User/Document/User/Seller.php',
  'User\Document\User\Validation'             => __DIR__ . '/src/User/Document/User/Validation.php',
  'User\Document\User'                        => __DIR__ . '/src/User/Document/User.php',
  'User\Helper\CronHelper'                    => __DIR__ . '/src/User/Helper/CronHelper.php',
  'User\Helper\EmailHelper'                   => __DIR__ . '/src/User/Helper/EmailHelper.php',
  'User\Helper\UserHelper'                    => __DIR__ . '/src/User/Helper/UserHelper.php',
  'User\Service\UserService'                  => __DIR__ . '/src/User/Service/UserService.php',
  'User\Validator\UserValidator'              => __DIR__ . '/src/User/Validator/UserValidator.php',
  'UserModuleTest\Bootstrap'                  => __DIR__ . '/tests/Bootstrap.php',
  'UserModuleTest\AbstractControllerZendtest' => __DIR__ . '/tests/UserModuleTest/AbstractControllerZendtest.php',
  'UserModuleTest\AbstractTestCase'           => __DIR__ . '/tests/UserModuleTest/AbstractTestCase.php',
  'UserModuleTest\Tests\UserTest'             => __DIR__ . '/tests/UserModuleTest/Tests/UserTest.php',
);
