<div class="account-centered-div account-rounded">
  <div class="row-fluid account-rounded">
    <div id="login_parent">
      <div class="span6 account-left account-rounded">
        <div class="account-inputs">
          <div class="row-fluid">
            <div class="span12">
              <div class="logo-login"><a href="/"><img src="/img/logo-hiperlytics.png" alt="logo" /></a></div>
            </div>
          </div>
        </div>
      </div>
      <div class="span6 account-info">
        <div class="account-inputs">
          <div class="row-fluid">
            <div class="span12">
              <div class="spacer-large"></div>
				<form id="form_login" enctype="application/x-www-form-urlencoded" action="/auth/login" method="post" novalidate="novalidate">
				<input type="hidden" name="formAction" value="formLogin" id="formAction" />
                <div id="form_login_1" class="step">
                  <p class="account-header">Sign In</p>
                 		<?php $this->flashMessenger()->html(); ?>

                  <div class="spacer-middle"></div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="email_login" type="text" name="email" class="input-block-level" placeholder="Email"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="password_login" type="password" name="password" class="input-block-level" placeholder="Password"/>
                    </div>
                  </div>
                  <div class="row-fluid">
                    <!--div class="span12"><a id="reset_link" href="javascript:showResetPassword();" class="pull-right">Forgot Password ?</a></div-->
                  </div>
                  <button type="submit" class="btn btn-large btn-yellow span7 pull-right">Sign In</button>

                  <div class="clearfix"></div>
                  <div class="spacer-small"></div>
                  <p id="signup_link">No account? <a href="javascript:showAccoount();">Sign up</a></p>
                  <p id="signup_link">Forgot Password? <a href="javascript:showResetPassword();">Get a new password</a></p>
                  <div class="spacer-middle"></div>
                </div>
              </form>
              <form id="form_reset" enctype="application/x-www-form-urlencoded" action="/auth/login" method="post" novalidate="novalidate" style="display:none;">
              	<input type="hidden" name="formAction" value="forgotForm" id="formAction" />
                <div id="form_reset-password" class="step">
                  <p class="account-header">Reset Password</p>
                  <div class="spacer-middle"></div>
                  <p>To begin the password reset process, enter your email and click &lsquo;Send&rsquo;</p>
                  <div class="spacer-middle"></div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="email_reset" type="text" name="email" class="input-block-level" placeholder="Email"/>
                    </div>
                  </div>
                  <div class="spacer-middle"></div>
                  <button type="button" onClick="javascript:hideResetPassword();" class="btn btn-large btn-gray span4 pull-left">Back</button>
                  <button type="submit" class="btn btn-large btn-yellow span7 pull-right">Send</button>
                  <div class="clearfix"></div>
                  <div class="spacer-large"></div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="account_parent" style="display:none;">
      <div class="span6 account-left account-rounded">
        <div class="account-inputs">
          <div class="row-fluid">
            <div class="span12">
              <div class="spacer-large"></div>
              <div class="logo-signup"><img src="/img/logo-hiperlytics.png" alt="logo" /></div>
              <div class="spacer-large"></div>
              <div class="spacer-large"></div>
              <p class="account-description">
	              	Free 30 Day Trial <br /><br />
	              	They say the best things in life are <strong>free.</strong>
	              	Our <strong>30 day trial</strong> is no exception. Register now and for 30 days you'll have access to
	              	the full version of Hiperlytics <strong>"Leasing Analysis Gone Mobile"</strong>
              </p>
              <div class="spacer-small"></div>
              <!--a href="#" class="account-link">Nullam quis risus urna mollis ornare ?</a-->
              </div>
          </div>
        </div>
      </div>
      <div class="span6 account-info">
        <div class="account-inputs">
          <div class="row-fluid">
            <div class="span12">
              <div class="spacer-large"></div>
              <form id="form_wizard" enctype="application/x-www-form-urlencoded" action="/auth/login" method="post">
              	<input type="hidden" name="formAction" value="formSignup" id="formAction" />
                <div id="form_wizard_1" class="step">
                  <!--p class="account-right-marginal"><span class="account-marginal-header">1/2</span>Personal Info</p-->
                  <p class="account-right-marginal">Sign Up</p>
                  <div class="spacer-middle"></div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="firstname" type="text" name="firstname" class="input-block-level" placeholder="First Name"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="lastname" type="text" name="lastname" class="input-block-level" placeholder="Last Name"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="email_account" type="text" name="email" class="input-block-level" placeholder="Email"/>
                    </div>
                  </div>
                  <!--div class="control-group">
                    <div class="controls">
                      <input id="email2_account" type="text" name="email2" class="input-block-level" placeholder="Confirm Email"/>
                    </div>
                  </div-->
                  <div class="control-group">
                    <div class="controls">
                      <input id="password_account" type="password" name="password" class="input-block-level" placeholder="Password"/>
                    </div>
                  </div>
                  <!--div class="control-group">
                    <div class="controls">
                      <input id="password2_account" type="password" name="password2" class="input-block-level" placeholder="Confirm Password"/>
                    </div>
                  </div-->
                  <div class="spacer-middle"></div>
                  <!--button type="submit" class="btn btn-large btn-yellow span6 pull-right">Next</button-->
                  <button type="submit" class="btn btn-large btn-yellow span7 pull-right">Create Account</button>
                </div>
                <!--div id="form_wizard_2" class="step">
                  <p class="account-right-marginal"><span class="account-marginal-header">2/2</span>Business Info</p>
                  <div class="spacer-middle"></div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="company_account" type="text" name="company" class="input-block-level" placeholder="Company Name"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="title_account" type="text" name="title" class="input-block-level" placeholder="Your Title"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="address_account" type="text" name="address" class="input-block-level" placeholder="Address"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="city_account" type="text" name="city" class="input-block-level" placeholder="City"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
                      <input id="state_account" type="text" name="state" class="span8" placeholder="State"/>
                      <input id="zipCode_account" type="text" name="zipCode" class="span4" placeholder="Zip Code"/>
                    </div>
                  </div>
                  <div class="control-group">
                    <div class="controls">
						<?php echo $this->partial("geolocation/html/country-select.phtml", array("class" => "input-block-level", "id" => "country_account", "name" => "country")); ?>
                    </div>
                  </div>
                  <div class="spacer-middle"></div>
                  <button id="back" type="reset" class="btn btn-large btn-gray span4 pull-left">Back</button>
                  <button type="submit" class="btn btn-large btn-yellow span7 pull-right">Create Account</button>

                </div-->
              </form>
              <div class="clearfix"></div>
              <div class="spacer-small"></div>
              <p id="login_bak_link"><a href="javascript:showLogin();">&larr;&nbsp;Sign In</a></p>
              <div class="spacer-middle"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
