<div class="email-content" style="padding: 0px; margin: 0px;">

		<p style="padding: 40px 38px 37px 38px; margin: 0px; font-family: 'Helvetica'; font-weight: bold; font-size: 25px; color: #1B1D21; line-height: 32px">
			Your password has been changed.
		</p>
		<p style="padding: 0px 38px 35px 38px; margin: 0px; font-family: 'Helvetica'; font-weight: 100; font-size: 18px; color: #585E66; line-height: 32px">
			<?php echo _('This is your new password on'); ?> <?php echo $this->company; ?>: <strong><?php echo $this->password; ?></strong>
		</p>
</div>
