<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                         => __DIR__ . '/Module.php',
  'Application\Controller\IndexController'     => __DIR__ . '/src/Application/Controller/IndexController.php',
  'ApplicationTest\AbstractControllerZendtest' => __DIR__ . '/tests/ApplicationTest/AbstractControllerZendtest.php',
  'ApplicationTest\AbstractTestCase'           => __DIR__ . '/tests/ApplicationTest/AbstractTestCase.php',
  'ApplicationTest\Tests\GeoControllerTest'    => __DIR__ . '/tests/ApplicationTest/Tests/GeoControllerTest.php',
  'ApplicationTest\Tests\IndexControllerTest'  => __DIR__ . '/tests/ApplicationTest/Tests/IndexControllerTest.php',
  'ApplicationTest\Tests\SalesControllerTest'  => __DIR__ . '/tests/ApplicationTest/Tests/SalesControllerTest.php',
  'ApplicationTest\Tests\UserServiceTest'      => __DIR__ . '/tests/ApplicationTest/Tests/UserServiceTest.php',
  'ApplicationTest\Bootstrap'                  => __DIR__ . '/tests/Bootstrap.php',
);
